#
# This file contains configuration flags to customize your site
#

title: AI for Chemists
description: Curated directory of AI tools for chemical research
baseurl: ""
url: "https://aiforchemists.info" # Deine Domain
plugins:
  - jekyll-sitemap # Für SEO
tools:
  categories: ["Drug Discovery", "Molecular Modeling", "Lab Automation"]
