#
# This file contains configuration flags to customize your site
#

# Grundkonfiguration
title: AI for Chemists
description: The best AI tools for chemical research
baseurl: ""
url: "https://aiforchemists.info"
theme: minima  # Standard-Jekyll-Theme

# Custom-Einstellungen
tools:
  categories: ["Drug Discovery", "Molecular Modeling", "Lab Automation"]
