name: Auto Update

on:
  schedule:
    - cron: '0 3 * * *'  # täglich um 3 Uhr morgens
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: Node.js einrichten
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Abhängigkeiten installieren
        run: npm install

      - name: Tools entdecken (GPT-basiert)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: node scripts/discover-tools-gpt.mjs

      - name: Tool-Beschreibungen aktualisieren
        run: npm run fetch

      - name: Screenshots erstellen
        run: npm run screenshot

      - name: Detailseiten generieren
        run: npm run generate

      - name: Änderungen committen und pushen
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/tools.json content/tools/*.md content/screenshots/
          git commit -m "Automatische Aktualisierung der Tools"
          git push
        continue-on-error: true  # Falls nichts geändert wurde, nicht fehlschlagen

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: GitHub Pages konfigurieren
        uses: actions/configure-pages@v4

      - name: Seiten-Artefakt hochladen
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public  # Pfad zu deiner gebauten Seite (anpassen wenn nötig)

      - name: GitHub Pages deployen
        uses: actions/deploy-pages@v4
