name: Data Collection

on:
  schedule:
    - cron: '0 3 * * 0'  # Sonntag 3 Uhr
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  collect-data:
    runs-on: ubuntu-latest
    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Node.js einrichten
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Abhängigkeiten installieren
        run: npm install

      - name: Install Playwright-Browser
        run: npx playwright install --with-deps

      - name: Tools entdecken (GPT-basiert)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: node scripts/discover-tools-gpt.mjs

      - name: Tool-Beschreibungen aktualisieren
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: npm run fetch

      - name: Screenshots erstellen
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
        run: npm run screenshot

      - name: Änderungen committen und pushen
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/tools.json
          git diff --cached --quiet || git commit -m "Automatische Datenaktualisierung"
          git push
