name: Hugging Face Data Collection

on:
  schedule:
    - cron: '0 3 * * 0,2,4,6'  # Sonntag 3 Uhr
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Run Generator
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          node .github/scripts/discover-tools-hf.mjs
          
      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Actions"
          git add data/tools.json
          git commit -m "Auto-update tools"
          git push
