name: Hugging Face Data Collection

on:
  schedule:
    - cron: '0 3 * * 0,2,4,6'  # Sonntag, Dienstag, Donnerstag, Samstag um 3 Uhr
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # wichtig für git push

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: npm ci

      - name: Install interferences
        run: npm install @huggingface/inference

      - name: Install yaml
        run: npm install yaml

      - name: Run HF Prompt Script
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_PROMPT: |
            Please return a valid JSON array of exactly 10 objects representing AI tools in cheminformatics or drug discovery.

            Each object must include the following fields:
            - name
            - slug
            - url
            - short_description
            - long_description
            - tags
            - category

            ❗ The output MUST be:
            - A single valid JSON array (no YAML, no markdown, no list)
            - No explanation, no introduction, no bullet points
            - No numbering or prefixes in the "name" field
            - Do not wrap it in any object (e.g. { "data": [...] } is not allowed)
            - No text before or after the JSON array
        run: node scripts/test-hf-prompt.mjs

      - name: Commit & Push Changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
          if [[ `git status --porcelain` ]]; then
            git add data/tools.json data/discover-cache.json data/gpt-output.txt
            git commit -m "Auto-update tools"
            git push
          else
            echo "ℹ️  Keine Änderungen zum Commit."
          fi
