name: Hugging Face Data Collection

on:
  schedule:
    - cron: '0 3 * * 0,2,4,6'  # Sonntag, Dienstag, Donnerstag, Samstag um 3 Uhr
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # wichtig für git push

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: npm ci

       - name: Run HF Prompt Script
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_PROMPT: |
            Please list 10 current AI tools in cheminformatics or drug discovery that are NOT in the following list:
            - tool1
            - tool2

            Return a JSON array of objects with fields: name, slug, url, short_description, long_description, tags, category.
        run: node scripts/test-hf-prompt.mjs

      - name: Commit & Push Changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
          if [[ `git status --porcelain` ]]; then
            git add data/tools.json data/discover-cache.json
            git commit -m "Auto-update tools"
            git push
          else
            echo "ℹ️  Keine Änderungen zum Commit."
          fi
