name: Data Collection

on:
  schedule:
    - cron: '0 3 * * 0'
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  collect-data:
    runs-on: ubuntu-latest
    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Node.js einrichten
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Abhängigkeiten installieren
        run: npm install

      - name: Tools entdecken mit Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_PROMPT: |
            Please return a valid JSON array of exactly 10 objects representing AI tools in cheminformatics or drug discovery.

            Each object must include the following fields:
            - name
            - slug
            - url
            - short_description
            - long_description
            - tags
            - category

            ❗ The output MUST be:
            - A single valid JSON array (no YAML, no markdown, no list)
            - No explanation, no introduction, no bullet points
            - No numbering or prefixes in the "name" field
            - Do not wrap it in any object (e.g. { "data": [...] } is not allowed)
            - No text before or after the JSON array
        run: node scripts/discover-tools-gpt.mjs

      - name: Tool-Beschreibungen vervollständigen
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: node scripts/fetch-tools-gpt.mjs

      - name: Änderungen committen und pushen
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/tools.json data/discover-cache.json data/description-cache.json data/gpt-output.txt
          git diff --cached --quiet || git commit -m "Automatische Datenaktualisierung (HF)"
          git push
