name: Screenshot Sync

on:
  schedule:
    - cron: "0 */12 * * *"  # Alle 12 Stunden
  workflow_dispatch:        # Manuell auslösbar

jobs:
  screenshot-job:
    runs-on: ubuntu-latest

    steps:
      - name: 🧾 Repo klonen
        uses: actions/checkout@v3

      - name: 🧰 Node.js einrichten
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📦 Abhängigkeiten installieren
        run: npm install

      - name: 📸 Screenshots generieren & tools.json aktualisieren
        run: npm run screenshot

      - name: 💾 Änderungen committen
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/tools.json
          git commit -m "Auto: Update screenshots [skip ci]" || echo "Keine Änderungen"
          git push
