name: Screenshot und Seitengenerierung

on:
  schedule:
    - cron: '0 4 * * 0'  # Sonntag 4 Uhr
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Clean install
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Install Playwright-Browser
        run: npx playwright install --with-deps

      - name: Screenshots erstellen und ungültige Tools entfernen
        env:
          CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
        run: npm run screenshot

      - name: Generate detail pages
        run: npm run generate
        
      - name: Last updated setzen
        run: |
          mkdir -p data
          echo "{ \"updated\": \"$(date -u +"%Y-%m-%dT%H:%M:%SZ")\" }" > data/last-updated.json

      - name: Änderungen committen und pushen
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add -A
          git diff --cached --quiet || git commit -m "Automatische Aktualisierung der Tools und Timestamp"

          # Kein Rebase – normaler Merge
          git pull origin main

          # Push mit PAT
          git remote set-url origin https://x-access-token:${PAT_TOKEN}@github.com/derkikumpel/aiforchemists.git
          git push origin HEAD:main

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'   # Gesamtes Repo root deployen (index.html + tools/)

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
